### ISSUE TITLE
Error importing from the Crypto Lib

### ISSUE THREAD

**Issue by edwardpopoola** [Flutterwave/flutterwave-python#7]
Python 2.7 (r27:82500, Feb  9 2016, 22:57:17)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from flutterwave import Flutterwave
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/flutterwave/__init__.py", line 1, in <module>
    from flutterwave import Flutterwave
  File "/usr/local/lib/python2.7/site-packages/flutterwave/flutterwave.py", line 1, in <module>
    from utils import Utils
  File "/usr/local/lib/python2.7/site-packages/flutterwave/utils.py", line 3, in <module>
    from Crypto.Cipher import DES3
ImportError: No module named Crypto.Cipher

**Comment by obinna-jesse** [comment]
@edwardpopoola pycrypto is required on linux systems for the crypto library. This has been updated.
